use std::fmt::Write as _;

struct IconModule {
    name: &'static str,
    label: &'static str,
    symbol: &'static str,
}

const ICON_MODULE_FORMAT: &str = "[ $symbol]($style)";
const ICON_MODULES: &[IconModule] = &[
    IconModule {
        name: "package",
        label: "Package",
        symbol: "",
    },
    IconModule {
        name: "python",
        label: "Python",
        symbol: "",
    },
    IconModule {
        name: "nodejs",
        label: "Node.js",
        symbol: "",
    },
    IconModule {
        name: "rust",
        label: "Rust",
        symbol: "",
    },
    IconModule {
        name: "golang",
        label: "Go",
        symbol: "",
    },
    IconModule {
        name: "java",
        label: "Java",
        symbol: "",
    },
    IconModule {
        name: "lua",
        label: "Lua",
        symbol: "",
    },
    IconModule {
        name: "ruby",
        label: "Ruby",
        symbol: "",
    },
    IconModule {
        name: "php",
        label: "PHP",
        symbol: "",
    },
    IconModule {
        name: "kotlin",
        label: "Kotlin",
        symbol: "",
    },
    IconModule {
        name: "swift",
        label: "Swift",
        symbol: "",
    },
    IconModule {
        name: "zig",
        label: "Zig",
        symbol: "",
    },
    IconModule {
        name: "gleam",
        label: "Gleam",
        symbol: "",
    },
    IconModule {
        name: "nix_shell",
        label: "Nix shell",
        symbol: "",
    },
];

pub fn render_yazelix_starship_config() -> String {
    let mut out = String::new();
    out.push_str(
        r#"# ========================================
# YAZELIX STARSHIP CONFIG FOR YAZI SIDEBAR
# ========================================
# This file is automatically generated by Yazelix.
# Do not edit directly; run `cargo run --bin generate_yazelix_starship > yazelix_starship.toml`.
#
# Compact starship prompt optimized for narrow sidebar display.
# Nerd Font icons only, no versions - keeps it legible in the one-row header.
#
# Example: "yazelix main  "
# ========================================

format = """
$directory\
$git_branch\
$git_status\
"#,
    );
    for module in ICON_MODULES {
        writeln!(out, "${}\\", module.name).unwrap();
    }
    out.push_str(
        r#""""

# Directory - show only current folder name
[directory]
truncation_length = 1
truncate_to_repo = false
format = "[$path]($style)"

# Git branch - space separated
[git_branch]
format = "[ $branch]($style)"
symbol = ""

# Git status - space separated
[git_status]
format = "[ ($all_status$ahead_behind)]($style)"
conflicted = "="
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
up_to_date = ""
untracked = "?"
stashed = "\\$"
modified = "!"
staged = "+"
renamed = "r"
deleted = "x"

"#,
    );
    for module in ICON_MODULES {
        writeln!(
            out,
            "# {} - icon only\n[{}]\nformat = \"{}\"\nsymbol = \"{}\"\n",
            module.label, module.name, ICON_MODULE_FORMAT, module.symbol
        )
        .unwrap();
    }
    out.push_str(
        r#"# Disable time-based modules
[cmd_duration]
disabled = true

[time]
disabled = true
"#,
    );
    out
}
