use std::fmt::Write as _;

const ICON_MODULE_FORMAT: &str = "[ $symbol]($style)";
const ICON_MODULES: &[(&str, &str)] = &[
    ("shlvl", "󰹍"),
    ("singularity", ""),
    ("kubernetes", "󱃾"),
    ("nats", ""),
    ("docker_context", ""),
    ("package", ""),
    ("bun", ""),
    ("c", ""),
    ("cmake", ""),
    ("cobol", ""),
    ("cpp", ""),
    ("daml", "󰘧"),
    ("dart", ""),
    ("deno", ""),
    ("dotnet", ""),
    ("elixir", ""),
    ("elm", ""),
    ("erlang", ""),
    ("fennel", ""),
    ("fortran", ""),
    ("gleam", ""),
    ("golang", ""),
    ("gradle", ""),
    ("haskell", ""),
    ("haxe", ""),
    ("helm", ""),
    ("java", ""),
    ("julia", ""),
    ("kotlin", ""),
    ("lua", ""),
    ("maven", ""),
    ("mojo", "󰈸"),
    ("nim", ""),
    ("nodejs", ""),
    ("ocaml", ""),
    ("odin", "󰟢"),
    ("opa", ""),
    ("perl", ""),
    ("php", ""),
    ("pulumi", ""),
    ("purescript", ""),
    ("python", ""),
    ("quarto", "󰂺"),
    ("raku", "󱖊"),
    ("rlang", "󰟔"),
    ("red", "󱍼"),
    ("ruby", ""),
    ("rust", ""),
    ("scala", ""),
    ("solidity", ""),
    ("swift", ""),
    ("terraform", ""),
    ("typst", ""),
    ("vlang", ""),
    ("vagrant", ""),
    ("xmake", ""),
    ("zig", ""),
    ("buf", ""),
    ("guix_shell", ""),
    ("nix_shell", ""),
    ("conda", ""),
    ("pixi", "󰏗"),
    ("meson", "󰔷"),
    ("spack", ""),
    ("memory_usage", "󰍛"),
    ("aws", ""),
    ("gcloud", "󱇶"),
    ("openstack", ""),
    ("azure", ""),
    ("direnv", ""),
    ("mise", ""),
    ("crystal", ""),
    ("sudo", ""),
    ("jobs", ""),
    ("battery", ""),
    ("status", ""),
    ("container", ""),
    ("netns", "󰛳"),
];

pub fn render_yazelix_starship_config() -> String {
    let mut out = String::new();
    out.push_str(
        r#"# ========================================
# YAZELIX STARSHIP CONFIG FOR YAZI SIDEBAR
# ========================================
# This file is automatically generated by Yazelix.
# Do not edit directly; run `cargo run --bin generate_yazelix_starship > yazelix_starship.toml`.
#
# Compact starship prompt optimized for narrow sidebar display.
# Directory and Git keep compact text; contextual modules render Nerd Font icons only.
#
# Example: "yazelix main  "
# ========================================

format = """
$hostname\
$directory\
$git_branch\
$git_status\
"#,
    );
    for &(name, _) in ICON_MODULES {
        writeln!(out, "${name}\\").unwrap();
    }
    out.push_str("\"\"\"\n\n");
    for &(name, symbol) in ICON_MODULES {
        write!(out, "{name} = {{ format = \"{ICON_MODULE_FORMAT}\"").unwrap();
        if !symbol.is_empty() {
            write!(out, ", symbol = \"{symbol}\"").unwrap();
        }
        out.push_str(" }\n");
    }
    out.push_str(
        r#"
# SSH host - icon only
[hostname]
format = "[ $ssh_symbol]($style)"
ssh_symbol = ""

# Directory - show only current folder name
[directory]
truncation_length = 1
truncate_to_repo = false
format = "[$path]($style)"

# Git branch - space separated
[git_branch]
format = "[ $branch]($style)"
symbol = ""

# Git status - space separated
[git_status]
format = "[ ($all_status$ahead_behind)]($style)"
conflicted = "="
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
up_to_date = ""
untracked = "?"
stashed = "\\$"
modified = "!"
staged = "+"
renamed = "r"
deleted = "x"

"#,
    );
    out.push_str(
        r#"# Disable time-based modules
[cmd_duration]
disabled = true

[time]
disabled = true
"#,
    );
    out
}
